### ISSUE TITLE
obsolete patch

### ISSUE THREAD

**Issue by nim65s** [Gepetto/omniORBpy#1]
Hi @jcarpent,

omniORBpy v4.2.4 has been released, and 033749c has been applied upstream.
So I this repository is now obsolete, isn't it ?

https://www.omniorb-support.com/pipermail/omniorb-list/2020-April/032107.html

**Comment by jcarpent** [comment]
Yes, certainly. I would keep it alive.

**Comment by jcarpent** [comment]
By the way, I need this repo to deploy on OSX.
